global:
    ros__parameters:
        autodatum: "auto"
        altitude: true
        #input_topics:
        fix: "gnss/fix"
        orientation: "compass/radians"
        units: "radians" # "degrees" or "radians"
